name: Setup Java

on:
  workflow_call: {}

jobs:
  setup-java:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9477386

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
